{{- if .Values.client.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
  {{- with .Values.client.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.client.ingress.className }}
  ingressClassName: {{ .Values.client.ingress.className }}
  {{- end }}
  {{- if .Values.client.ingress.tls }}
  tls:
    {{- toYaml .Values.client.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.client.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Release.Name }}-client
                port:
                  number: {{ $.Values.client.service.port | default 80 }}
          {{- end }}
    {{- end }}
{{- end }}