apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-blog-app.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-blog-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  selector:
    {{- include "my-blog-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
  ports:
    - name: http 
      protocol: TCP
      port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}