apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount | default .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "blog-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "blog-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
      {{- if .Values.client.podAnnotations }}
      annotations:
        {{- toYaml .Values.client.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.client.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.targetPort | default 80 }}
              protocol: TCP
          env:
            {{- if .Values.client.env }}
            {{- toYaml .Values.client.env | nindent 12 }}
            {{- end }}
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: backendApiUrl
                  optional: true
          {{- include "blog-app.livenessProbe" . | nindent 10 }}
          {{- include "blog-app.readinessProbe" . | nindent 10 }}
          {{- if .Values.client.resources }}
          {{- toYaml .Values.client.resources | nindent 10 }}
          {{- else }}
          {{- include "blog-app.resources" . | nindent 10 }}
          {{- end }}