apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-blog-app.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-blog-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "my-blog-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}