apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blog-project
  source:
    repoURL: https://github.com/Aman3899/DevOps_Assignment_01.git
    targetRevision: main
    path: kubernetes/helm/my-app
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences: []
  revisionHistoryLimit: 10