apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLWRldg==
  MONGO_URI: bW9uZ29kYjovL2Rldi11c2VyOmRldi1wYXNzd29yZEBtb25nby0wLm1vbmdvLXN2Yy5kZXYuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvYmxvZ2RiP2F1dGhTb3VyY2U9YWRtaW4= # Replace with your actual base64 encoded MongoDB connection string for dev

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: ZGV2LXVzZXI=
  password: ZGV2LXBhc3N3b3Jk