apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: aman3899/backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: blog-app-config
                  key: BASE_API_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-app-secrets
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: blog-app-secrets
                  key: MONGO_URI