replicaCount: 1 

imagePullPolicy: IfNotPresent 

# --- Client (Frontend) Configuration ---
client:
  image:
    repository: aman3899/frontend
    tag: "latest"
  service:
    type: ClusterIP
    port: 80 
    targetPort: 8080
  resources: 
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  ingress:
    enabled: true
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
    tls: [] 

# --- Server (Backend) Configuration ---
server:
  image:
    repository: aman3899/backend
    tag: "latest"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001 
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

# --- MongoDB Configuration ---
mongodb:
  image:
    repository: mongo
    tag: "5.0"
  serviceName: "mongo-svc"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  persistence:
    enabled: true
    size: 2Gi
appConfigData:
  BASE_API_URL: "http://localhost:3001"
  backendApiUrl: "http://localhost:3001/api"
appSecretData:
  JWT_SECRET: ""
  MONGO_URI: ""
mongoSecretData:
  username: ""
  password: ""