apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: frontend-service.myapp.svc.cluster.local
  namespace: myapp
spec:
  routes:
  - name: "GET /"
    condition:
      method: GET
      pathRegex: "/"
    isRetryable: true
    timeout: 500ms
  - name: "GET /health"
    condition:
      method: GET
      pathRegex: "/health"
    isRetryable: false